version: '3.9'

services:
  app:
    build:
      context: .
      target: server-build
    command: reflex -r '(\.go$$|go\.mod)' -s go run cmd/markednotes/markednotes.go
    volumes: 
      - .:/app
    ports: 
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/markednotes
      - PORT=8080
      - SIGNING_KEY=supersecretkey
    depends_on:
      - db
  
  vue:
    build:
      context: .
      target: client-build
    command: npm run dev
    volumes:
      - ./vue:/app
    ports:
      - "3000:3000"
    depends_on:
      - app

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=markednotes
      - POSTGRES_PASSWORD=postgres

volumes:
  db_data:
